name: Android CI

on: [push, pull_request]

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.3.4

      - name: Compute key for CI cache
        run: ./scripts/compute-ci-cache-key.sh key.txt

      - name: Setup Cache
        uses: actions/cache@v2.1.4
        continue-on-error: true
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('key.txt') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Gradle Cache
        uses: actions/cache@v2.1.4
        id: gradle-cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('buildSrc/src/main/kotlin/Dependencies.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Optimize for Gradle build
        run: |
          mkdir -p ~/.gradle
          cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Run Tests
        run: ./gradlew clean testPinboardapiDebugUnitTest --stacktrace

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Setup Cache
        uses: actions/cache@v2.1.4
        continue-on-error: true
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('key.txt') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Gradle Cache
        uses: actions/cache@v2.1.4
        id: gradle-cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('buildSrc/src/main/kotlin/Dependencies.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Optimize for Gradle build
        run: |
          mkdir -p ~/.gradle
          cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Build
        run: ./gradlew clean assemblePinboardapi --stacktrace

      - name: Upload Pinboard API APK
        uses: actions/upload-artifact@v2.2.1
        with:
          path: app/build/outputs/apk/pinboardapi/debug/app-pinboardapi-debug.apk

  instrumented_tests:
    name: Instrumented Tests
    runs-on: macOS-latest
    needs: [unit_tests, build]
    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Setup Cache
        uses: actions/cache@v2.1.4
        continue-on-error: true
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('key.txt') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Gradle Cache
        uses: actions/cache@v2.1.4
        id: gradle-cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('buildSrc/src/main/kotlin/Dependencies.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Optimize for Gradle build
        run: |
          mkdir -p ~/.gradle
          cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2.14.3
        with:
          api-level: 29
          arch: x86_64
          script: ./gradlew clean :app:connectedAndroidTest --stacktrace
